package registry

import (
	"bytes"
	"html/template"
	"regexp"

	grantedConfig "github.com/common-fate/granted/pkg/config"
)

const AUTO_GENERATED_MSG string = `# Granted-Registry Autogenerated Section. DO NOT EDIT.
# This section is automatically generated by Granted (https://granted.dev). Manual edits to this section will be overwritten.
# To edit, clone your profile registry repo, edit granted.yml, and push your changes. You may need to make a pull request depending on the repository settings.
# To stop syncing and remove this section, run 'granted registry remove'.`

func getAutogeneratedTemplate() string {
	return AUTO_GENERATED_MSG
}

type ConfigTemplateVariables struct {
	Required  map[string]string
	Variables map[string]string
	Profile   string
}

func interpolateVariables(r *Registry, value string, profileName string) (string, error) {
	gConf, err := grantedConfig.Load()
	if err != nil {
		return "", err
	}

	d := ConfigTemplateVariables{
		Variables: gConf.ProfileRegistry.Variables,
		Required:  gConf.ProfileRegistry.RequiredKeys,
		Profile:   profileName,
	}

	tmpl, err := template.New("registry-variable").Parse(value)
	if err != nil {
		return "", err
	}

	buf := &bytes.Buffer{}
	err = tmpl.Execute(buf, d)
	if err != nil {
		panic(err)
	}
	return buf.String(), nil
}

func containsTemplate(text string) bool {
	re := regexp.MustCompile(`{{\s+(.\w+){1,2}\s+}}`)

	return re.MatchString(text)
}
